[[stack]]
name = "enceladus-core"
tags = ["enceladus"]
[stack.config]
server = "enceladus"
project_name = "core"
links = ["https://traefik.enceladus.jekotia.net"]
git_account = "jekotia"
repo = "jekotia/enceladus"
branch = "main"
webhook_enabled = false
run_directory = "docker/stacks/core/"
file_paths = [
  "compose.yaml",
  "portainer.yaml",
  "traefik.yaml"
]
environment = """
TIMEZONE=[[TIMEZONE]]

TRAEFIK_URL_PREFIX=traefik.enceladus.
NETWORK_DOMAIN=[[NETWORK_DOMAIN]]

SECRETS_CLOUDFLARE_API_KEY=[[ENCELADUS_TRAEFIK_CLOUDFLARE_API_TOKEN]]
SECRETS_CLOUDFLARE_EMAIL=[[SECRETS_CLOUDFLARE_EMAIL]]

#########-> DANGER ZONE <-#########
UID=1000
GID=1000
"""